### PR TITLE
Add option to open as app window

### PR DESCRIPTION
**Pull request by chenasraf**
This adds a question to the creation that asks whether to open in
Chrome’s “app” mode, which just removes the toolbars from the window.
This ends up with a simple window with a title and buttons, and no
tabs/toolbar icons/bookmarks bar, etc., making it look like a
standalone app.

### CODE REVIEW

**Comment by golderhub** [comment]
This would be awesome

**Comment by ittaiz** [comment]
@maxkostow Any chance this will go in?

**Comment by maxkostow** [comment]
As written, this doesn't work. You need to add a space before the `gExcludeToolbar` is inserted into the command string.

**Comment by maxkostow** [comment]
Otherwise, I'd be happy to merge.

**Comment by ittaiz** [comment]
you mean that instead of `set gExcludeToolbar to "--app="` it should say `set gExcludeToolbar to " --app="`?

**Comment by chenasraf** [comment]
@maxkostow fixed, added the space in the exec line instead

**Comment by ittaiz** [comment]
Thanks!

‏בתאריך יום רביעי, 4 בפברואר 2015, Chen Asraf notifications@github.com
כתב:

**Pull request merged**
